# Import

In [125]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline

In [126]:
pitHicAllStUnclean = pd.read_excel('output_files_paso1_unclean/pitHicAllStUnclean.xlsx', index_col=0)
pitHicAllCocUnclean = pd.read_excel('output_files_paso1_unclean/pitHicAllCocUnclean.xlsx', index_col=0)

In [127]:
pitHicAllCocClean = pitHicAllCocUnclean.copy(deep=True)
pitHicAllCocClean.drop('cocOnBoth', axis=1, inplace=True)
pitHicAllCocCleanGroups = pitHicAllCocClean.copy(deep=True)

In [128]:
pitHicAllStClean = pitHicAllStUnclean.copy(deep=True)

# Cleaned CoC data
***--> TWO OUTPUTS: combined per mergers, and combined mergers + MA and GA groups***

### Define and apply rename of CoCs that merged into other CoC

***The following adjustments need to be made:***<br>
AR-502 added into AR-503 for any year on PIT or HIC. *In same fashion add x: into :y for any year x appears on PIT or HIC, by first renaming old to new CoC numbers and then combining like numbers.*
<br>
*See the Excel file aligning CoCs to counties for details on which years this applies to each CoC below.*<br>
*With the exception of AR-502, AR-506, AR-509, AR-510, and CA-528 which appear on both the PIT and HIC files in early years, all were merged on the PIT but still appear on the HIC*.

'AR-502':'AR-503', 'AR-506':'AR-503', 'AR-507':'AR-503', 'AR-509':'AR-503', 'AR-510':'AR-503',<br>
'CA-528':'CA-516', 'CA-605':'CA-611', 'CA-610':'CA-601', 'CA-615':'CA-530',<br>
'CT-500':'CT-505', 'CT-501':'CT-505', 'CT-502':'CT-505', 'CT-504':'CT-505', 'CT-506':'CT-503', 'CT-507':'CT-505', 'CT-508':'CT-503', 'CT-509':'CT-505', 'CT-510':'CT-505', 'CT-512':'CT-505',<br>
'FL-516':'FL-503',<br>
'IL-505':'IL-511',<br>
'IN-500':'IN-502',<br>
'KS-500':'KS-507',<br>
'LA-501':'LA-509', 'LA-504':'LA-509',<br>
'MA-512':'MA-516', 'MA-513':'MA-516', 'MA-518':'MA-516', 'MA-520':'MA-511',<br>
'ME-501':'ME-500', 'ME-502':'ME-500',<br>
'MI-521':'MI-500', 'MI-522':'MI-500', 'MI-524':'MI-500',<br>
'MN-507':'MN-503', 'MN-510':'MN-503', 'MN-512':'MN-503',<br>
'KS-501':'MO-604',<br>
'MO-601':'MO-606',<br>
'NC-508':'NC-503',<br>
'NE-503':'NE-500', 'NE-504':'NE-500', 'NE-505':'NE-500', 'NE-506':'NE-500',<br>
'NJ-505':'NJ-503', 'NJ-517':'NJ-516', 'NJ-518':'NJ-503', 'NJ-519':'NJ-516', 'NJ-520':'NJ-503',<br>
'NY-502':'NY-505', 'NY-509':'NY-505', 'NY-515':'NY-511', 'NY-517':'NY-508', 'NY-521':'NY-518', 'NY-524':'NY-508', 'NY-605':'NY-603',<br>
'OR-504':'OR-505',<br>
'PA-507':'PA-509', 'PA-602':'PA-601',<br>
'SC-504':'SC-503',<br>
'TX-501':'TX-607', 'TX-504':'TX-607', 'TX-610':'TX-607', 'TX-613':'TX-607', 'TX-702':'TX-607', 'TX-703':'TX-607', 'TX-704':'TX-607',<br>
'VA-509':'VA-521', 'VA-510':'VA-521', 'VA-512':'VA-501', 'VA-517':'VA-521', 'VA-518':'VA-513', 'VA-519':'VA-501',<br>
'WA-506':'WA-502'

Also, the CA-527 in 2009 only (HIC only) needs to be added into CA-515.

Also note that, still, MA-501 and MA-514 are present on earlier years but cannot be merged anywhere (are handled in the grouping file)

In [129]:
cocMergersRename = {'AR-502':'AR-503', 'AR-506':'AR-503', 'AR-507':'AR-503', 'AR-509':'AR-503', 'AR-510':'AR-503', 
              'CA-528':'CA-516', 'CA-605':'CA-611', 'CA-610':'CA-601', 'CA-615':'CA-530',
              'CT-500':'CT-505', 'CT-501':'CT-505', 'CT-502':'CT-505', 'CT-504':'CT-505', 'CT-506':'CT-503', 'CT-507':'CT-505', 'CT-508':'CT-503', 'CT-509':'CT-505', 'CT-510':'CT-505', 'CT-512':'CT-505', 
              'FL-516':'FL-503', 
              'IL-505':'IL-511', 
              'IN-500':'IN-502',
              'KS-500':'KS-507', 
              'LA-501':'LA-509', 'LA-504':'LA-509',
              'MA-512':'MA-516', 'MA-513':'MA-516', 'MA-518':'MA-516', 'MA-520':'MA-511',
              'ME-501':'ME-500', 'ME-502':'ME-500',
              'MI-521':'MI-500', 'MI-522':'MI-500', 'MI-524':'MI-500', 
              'MN-507':'MN-503', 'MN-510':'MN-503', 'MN-512':'MN-503', 
              'KS-501':'MO-604', 
              'MO-601':'MO-606', 
              'NC-508':'NC-503', 
              'NE-503':'NE-500', 'NE-504':'NE-500', 'NE-505':'NE-500', 'NE-506':'NE-500', 
              'NJ-505':'NJ-503', 'NJ-517':'NJ-516', 'NJ-518':'NJ-503', 'NJ-519':'NJ-516', 'NJ-520':'NJ-503', 
              'NY-502':'NY-505', 'NY-509':'NY-505', 'NY-515':'NY-511', 'NY-517':'NY-508', 'NY-521':'NY-518', 'NY-524':'NY-508', 'NY-605':'NY-603', 
              'OR-504':'OR-505', 
              'PA-507':'PA-509', 'PA-602':'PA-601', 
              'SC-504':'SC-503', 
              'TX-501':'TX-607', 'TX-504':'TX-607', 'TX-610':'TX-607', 'TX-613':'TX-607', 'TX-702':'TX-607', 'TX-703':'TX-607', 'TX-704':'TX-607', 
              'VA-509':'VA-521', 'VA-510':'VA-521', 'VA-512':'VA-501', 'VA-517':'VA-521', 'VA-518':'VA-513', 'VA-519':'VA-501', 
              'WA-506':'WA-502'}

In [130]:
pitHicAllCocClean.rename(index = cocMergersRename, inplace=True)

*Apply some additional mergers for the grouped dataset version*

In [131]:
#The following should be grouped in order to compare back to 2007.
#Otherwise, don't compare back before what is indicated to be the comparable-to year.

cocGroupsRename = {'GA-500':'GA-GR1', 'GA-502':'GA-GR1', 'GA-508':'GA-GR1',
                   'MA-501':'MA-GR1', 'MA-504':'MA-GR1', 'MA-507':'MA-GR1',
                   'MA-514':'MA-GR2', 'MA-516':'MA-GR2', 'MA-517':'MA-GR2',
                  }
                 #NOTE: MA-501 and MA-514 no longer exist but are on earlier years. They weren't cleanly merged into another.

In [132]:
pitHicAllCocCleanGroups.rename(index = cocMergersRename, inplace=True)
pitHicAllCocCleanGroups.rename(index = cocGroupsRename, inplace=True)

*Test the renaming result. CoC #'s that merged should be found in the Unclean dataset but not the Clean dataset.<br>
Likewise, the Clean dataset should throw and error for the old CoC # and have extra records for the CoC # into which another CoC merged.*

pitHicAllCocUnclean.loc['CA-615']

pitHicAllCocClean.loc['CA-615']

pitHicAllCocCleanGroups.loc['MA-GR2']

### Rename of CA-527 for 2009 only

In [133]:
pitHicAllCocClean.reset_index(inplace=True)
pitHicAllCocCleanGroups.reset_index(inplace=True)

In [134]:
pitHicAllCocClean['cocNum'] = np.where(((pitHicAllCocClean['cocNum']=='CA-527')&(pitHicAllCocClean['year']==2009)), 'CA-511', pitHicAllCocClean['cocNum'])
pitHicAllCocCleanGroups['cocNum'] = np.where(((pitHicAllCocCleanGroups['cocNum']=='CA-527')&(pitHicAllCocCleanGroups['year']==2009)), 'CA-511', pitHicAllCocCleanGroups['cocNum'])

*Test the results*

In [135]:
pitHicAllCocClean[pitHicAllCocClean.loc[:,'cocNum']=='CA-527']
pitHicAllCocCleanGroups[pitHicAllCocCleanGroups.loc[:,'cocNum']=='CA-527']

,cocNum,year,cocName,st_x,totalH,shelH,unshelH,totalIndiv,shelIndiv,unshelIndiv,...,rrhBedsDedVet,pshBedsDedVet,ophBedsDedVet,esBedsDedYouth,thBedsDedYouth,shBedsDedYouth,rrhBedsDedYouth,pshBedsDedYouth,ophBedsDedYouth,pshBedsDedCh
515,CA-527,2015,Tehama County CoC,CA,138.0,78.0,60.0,115.0,60.0,55.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
516,CA-527,2016,Tehama County CoC,CA,133.0,73.0,60.0,103.0,48.0,55.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
517,CA-527,2017,Tehama County CoC,CA,124.0,68.0,56.0,103.0,47.0,56.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [136]:
pitHicAllCocClean[pitHicAllCocClean.loc[:,'cocNum']=='CA-511']
pitHicAllCocCleanGroups[pitHicAllCocCleanGroups.loc[:,'cocNum']=='CA-511']

,cocNum,year,cocName,st_x,totalH,shelH,unshelH,totalIndiv,shelIndiv,unshelIndiv,...,rrhBedsDedVet,pshBedsDedVet,ophBedsDedVet,esBedsDedYouth,thBedsDedYouth,shBedsDedYouth,rrhBedsDedYouth,pshBedsDedYouth,ophBedsDedYouth,pshBedsDedCh
338,CA-511,2007,Stockton/San Joaquin County CoC,CA,2479.0,2176.0,303.0,1657.0,1417.0,240.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,121.0
339,CA-511,2008,Stockton/San Joaquin County CoC,CA,2354.0,2051.0,303.0,1532.0,1292.0,240.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,121.0
340,CA-511,2009,Stockton/San Joaquin County CoC,CA,3005.0,2840.0,165.0,2122.0,1957.0,165.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,121.0
341,CA-511,2010,Stockton/San Joaquin County CoC,CA,3005.0,2840.0,165.0,2122.0,1957.0,165.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,121.0
342,CA-511,2011,Stockton/San Joaquin County CoC,CA,2540.0,2293.0,247.0,1538.0,1316.0,222.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,145.0
343,CA-511,2012,Stockton/San Joaquin County CoC,CA,1569.0,1322.0,247.0,739.0,517.0,222.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,138.0
344,CA-511,2013,Stockton/San Joaquin County CoC,CA,1541.0,1278.0,263.0,794.0,556.0,238.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,169.0
345,CA-511,2014,Stockton/San Joaquin County CoC,CA,1588.0,1325.0,263.0,713.0,475.0,238.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
346,CA-511,2015,Stockton/San Joaquin County CoC,CA,1708.0,1173.0,535.0,957.0,470.0,487.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
347,CA-511,2016,Stockton/San Joaquin County CoC,CA,1780.0,1245.0,535.0,947.0,460.0,487.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
348,CA-511,2017,Stockton/San Joaquin County CoC,CA,1542.0,975.0,567.0,1016.0,467.0,549.0,...,28.0,355.0,0.0,10.0,8.0,0.0,0.0,37.0,0.0,186.0
514,CA-511,2009,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0

### Perform the merge via 2-column groupby and .sum

In [137]:
#combine duplicate coc numbers in the same year
pitHicAllCocClean = pitHicAllCocClean.groupby(by=['cocNum','year']).sum()
pitHicAllCocCleanGroups = pitHicAllCocCleanGroups.groupby(by=['cocNum','year']).sum()
pitHicAllCocClean.head(3)

             totalH   shelH  unshelH  totalIndiv  shelIndiv  unshelIndiv  \
cocNum year
AK-500 2007   974.0   842.0    132.0       696.0      589.0        107.0
       2008  1023.0   921.0    102.0       695.0      596.0         99.0
       2009  1267.0  1110.0    157.0       821.0      689.0        132.0

             totalInFam  shelInFam  unshelInFam  totalChronic      ...       \
cocNum year                                                        ...
AK-500 2007       278.0      253.0         25.0         224.0      ...
       2008       328.0      325.0          3.0         300.0      ...
       2009       446.0      421.0         25.0         198.0      ...

             rrhBedsDedVet  pshBedsDedVet  ophBedsDedVet  esBedsDedYouth  \
cocNum year
AK-500 2007            NaN            NaN            NaN             NaN
       2008            NaN            NaN            NaN             NaN
       2009            NaN            NaN            NaN             NaN

             thBedsDedYouth  shBedsDedYouth  rrhBedsDedYouth  pshBedsDedYouth  \
cocNum year
AK-500 2007             NaN             NaN              NaN              NaN
       2008             NaN             NaN              NaN              NaN
       2009             NaN             NaN              NaN              NaN

             ophBedsDedYouth  pshBedsDedCh
cocNum year
AK-500 2007              NaN         121.0
       2008              NaN         121.0
       2009              NaN          27.0

[3 rows x 110 columns]

*Test the results*

pitHicAllCocClean.loc['AR-503']

pitHicAllCocClean.loc['CA-511']

pitHicAllCocCleanGroups.loc['MA-GR2']

## Clean up

### Restore CoC and state names (lost in groupby sum)

*Return to only cocNum as index*

In [138]:
pitHicAllCocClean.reset_index(inplace=True)
pitHicAllCocClean.set_index('cocNum', inplace=True)

pitHicAllCocCleanGroups.reset_index(inplace=True)
pitHicAllCocCleanGroups.set_index('cocNum', inplace=True)

In [139]:
#To see which non-summable columns were lost between the Clean and the Unclean datasets
set(pitHicAllCocClean.columns.values) ^ set(pitHicAllCocUnclean.columns.values)

{'cocName', 'cocOnBoth', 'st_x', 'st_y'}

In [140]:
#Convert the cocNum/cocName columns from the Unclean dataset to a dictionary
cocNumName = pitHicAllCocUnclean['cocName'].to_dict()
#cocNumName

In [141]:
pitHicAllCocClean['cocName'] = pitHicAllCocClean.index  #set as cocNum temporarily to then replace
pitHicAllCocClean.replace(to_replace={'cocName':cocNumName}, inplace=True)

pitHicAllCocCleanGroups['cocName'] = pitHicAllCocCleanGroups.index  #set as cocNum temporarily to then replace
pitHicAllCocCleanGroups.replace(to_replace={'cocName':cocNumName}, inplace=True)

pitHicAllCocClean.head(3)

,year,totalH,shelH,unshelH,totalIndiv,shelIndiv,unshelIndiv,totalInFam,shelInFam,unshelInFam,...,pshBedsDedVet,ophBedsDedVet,esBedsDedYouth,thBedsDedYouth,shBedsDedYouth,rrhBedsDedYouth,pshBedsDedYouth,ophBedsDedYouth,pshBedsDedCh,cocName
cocNum,,,,,,,,,,,,,,,,,,,,,
AK-500,2007,974.0,842.0,132.0,696.0,589.0,107.0,278.0,253.0,25.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,121.0,Anchorage CoC
AK-500,2008,1023.0,921.0,102.0,695.0,596.0,99.0,328.0,325.0,3.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,121.0,Anchorage CoC
AK-500,2009,1267.0,1110.0,157.0,821.0,689.0,132.0,446.0,421.0,25.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,27.0,Anchorage CoC

In [142]:
pitHicAllCocClean['st'] = pitHicAllCocClean.index.str[:2]

pitHicAllCocCleanGroups['st'] = pitHicAllCocCleanGroups.index.str[:2]

pitHicAllCocClean.head(3)

,year,totalH,shelH,unshelH,totalIndiv,shelIndiv,unshelIndiv,totalInFam,shelInFam,unshelInFam,...,ophBedsDedVet,esBedsDedYouth,thBedsDedYouth,shBedsDedYouth,rrhBedsDedYouth,pshBedsDedYouth,ophBedsDedYouth,pshBedsDedCh,cocName,st
cocNum,,,,,,,,,,,,,,,,,,,,,
AK-500,2007,974.0,842.0,132.0,696.0,589.0,107.0,278.0,253.0,25.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,121.0,Anchorage CoC,AK
AK-500,2008,1023.0,921.0,102.0,695.0,596.0,99.0,328.0,325.0,3.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,121.0,Anchorage CoC,AK
AK-500,2009,1267.0,1110.0,157.0,821.0,689.0,132.0,446.0,421.0,25.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,27.0,Anchorage CoC,AK

### Re-order column names

In [143]:
#Some index shuffling to move st, cocName, and year to the front
pitHicAllCocClean.reset_index(inplace=True)
pitHicAllCocClean.set_index(['cocNum','st','cocName','year'], inplace=True)
pitHicAllCocClean.reset_index(inplace=True)
pitHicAllCocClean.set_index(['cocNum'], inplace=True)

pitHicAllCocCleanGroups.reset_index(inplace=True)
pitHicAllCocCleanGroups.set_index(['cocNum','st','cocName','year'], inplace=True)
pitHicAllCocCleanGroups.reset_index(inplace=True)
pitHicAllCocCleanGroups.set_index(['cocNum'], inplace=True)

### Double check totals

In [144]:
#Comparing the new cocClean ... 
totalsCheckCoc = pitHicAllCocClean.groupby('year').sum()
totalsCheckCoc

,totalH,shelH,unshelH,totalIndiv,shelIndiv,unshelIndiv,totalInFam,shelInFam,unshelInFam,totalChronic,...,rrhBedsDedVet,pshBedsDedVet,ophBedsDedVet,esBedsDedYouth,thBedsDedYouth,shBedsDedYouth,rrhBedsDedYouth,pshBedsDedYouth,ophBedsDedYouth,pshBedsDedCh
year,,,,,,,,,,,,,,,,,,,,,
2007,647258.0,391401.0,255857.0,412700.0,213073.0,199627.0,234558.0,178328.0,56230.0,119813.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,37793.0
2008,639784.0,386361.0,253423.0,404525.0,204855.0,199670.0,235259.0,181506.0,53753.0,120115.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,42298.0
2009,630227.0,403308.0,226919.0,392131.0,215995.0,176136.0,238096.0,187313.0,50783.0,107212.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,50602.0
2010,637077.0,403543.0,233534.0,395140.0,212218.0,182922.0,241937.0,191325.0,50612.0,106062.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,55256.0
2011,623788.0,392316.0,231472.0,387613.0,205834.0,181779.0,236175.0,186482.0,49693.0,119033.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,67964.0
2012,621553.0,390155.0,231398.0,382156.0,199159.0,182997.0,239397.0,190996.0,48401.0,112037.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,74693.0
2013,590364.0,394698.0,195666.0,368174.0,203127.0,165047.0,222190.0,191571.0,30619.0,102828.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,81666.0
2014,576450.0,401051.0,175399.0,360189.0,209148.0,151041.0,216261.0,191903.0,24358.0,99132.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2015,564708.0,391440.0,173268.0,358422.0,205616.0,152806.0,206286.0,185824.0,20462.0,96275.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2016,549928.0,373571.0,176357.0,355212.0,198008.0,157204.0,194716.0,175563.0,19153.0,86132.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2017,553742.0,360867.0,192875.0,369081.0,193144.0,175937.0,184661.0,167723.0,16938.0,95419.0,...,18281.0,100652.0,1857.0,6140.0,10077.0,8.0,2323.0,4117.0,627.0,149005.0

In [145]:
#Comparing the new cocClean GROUPED ... 
totalsCheckCocGrouped = pitHicAllCocCleanGroups.groupby('year').sum()
totalsCheckCocGrouped

,totalH,shelH,unshelH,totalIndiv,shelIndiv,unshelIndiv,totalInFam,shelInFam,unshelInFam,totalChronic,...,rrhBedsDedVet,pshBedsDedVet,ophBedsDedVet,esBedsDedYouth,thBedsDedYouth,shBedsDedYouth,rrhBedsDedYouth,pshBedsDedYouth,ophBedsDedYouth,pshBedsDedCh
year,,,,,,,,,,,,,,,,,,,,,
2007,647258.0,391401.0,255857.0,412700.0,213073.0,199627.0,234558.0,178328.0,56230.0,119813.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,37793.0
2008,639784.0,386361.0,253423.0,404525.0,204855.0,199670.0,235259.0,181506.0,53753.0,120115.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,42298.0
2009,630227.0,403308.0,226919.0,392131.0,215995.0,176136.0,238096.0,187313.0,50783.0,107212.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,50602.0
2010,637077.0,403543.0,233534.0,395140.0,212218.0,182922.0,241937.0,191325.0,50612.0,106062.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,55256.0
2011,623788.0,392316.0,231472.0,387613.0,205834.0,181779.0,236175.0,186482.0,49693.0,119033.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,67964.0
2012,621553.0,390155.0,231398.0,382156.0,199159.0,182997.0,239397.0,190996.0,48401.0,112037.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,74693.0
2013,590364.0,394698.0,195666.0,368174.0,203127.0,165047.0,222190.0,191571.0,30619.0,102828.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,81666.0
2014,576450.0,401051.0,175399.0,360189.0,209148.0,151041.0,216261.0,191903.0,24358.0,99132.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2015,564708.0,391440.0,173268.0,358422.0,205616.0,152806.0,206286.0,185824.0,20462.0,96275.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2016,549928.0,373571.0,176357.0,355212.0,198008.0,157204.0,194716.0,175563.0,19153.0,86132.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2017,553742.0,360867.0,192875.0,369081.0,193144.0,175937.0,184661.0,167723.0,16938.0,95419.0,...,18281.0,100652.0,1857.0,6140.0,10077.0,8.0,2323.0,4117.0,627.0,149005.0

In [146]:
# ... to the STATE level dataset totals
totalsCheckSt = pitHicAllStUnclean.groupby('year').sum()
totalsCheckSt

,numCoCs,totalH,shelH,unshelH,totalIndiv,shelIndiv,unshelIndiv,totalInFam,shelInFam,unshelInFam,...,rrhBedsDedVet,pshBedsDedVet,ophBedsDedVet,esBedsDedYouth,thBedsDedYouth,shBedsDedYouth,rrhBedsDedYouth,pshBedsDedYouth,ophBedsDedYouth,pshBedsDedCh
year,,,,,,,,,,,,,,,,,,,,,
2007,461,647258,391401,255857,412700,213073,199627,234558,178328,56230,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,37793.0
2008,448,639784,386361,253423,404525,204855,199670,235259,181506,53753,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,42298.0
2009,450,630227,403308,226919,392131,215995,176136,238096,187313,50783,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,50602.0
2010,444,637077,403543,233534,395140,212218,182922,241937,191325,50612,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,55256.0
2011,432,623788,392316,231472,387613,205834,181779,236175,186482,49693,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,67964.0
2012,425,621553,390155,231398,382156,199159,182997,239397,190996,48401,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,74693.0
2013,415,590364,394698,195666,368174,203127,165047,222190,191571,30619,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,81666.0
2014,414,576450,401051,175399,360189,209148,151041,216261,191903,24358,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2015,406,564708,391440,173268,358422,205616,152806,206286,185824,20462,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2016,403,549928,373571,176357,355212,198008,157204,194716,175563,19153,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2017,400,553742,360867,192875,369081,193144,175937,184661,167723,16938,...,18281.0,100652.0,1857.0,6140.0,10077.0,8.0,2323.0,4117.0,627.0,149005.0

## Add column noting if reflects a merger in PIT and/or HIC

In [147]:
mergerNotes = {'AR-503':'AR-509, AR-510 pithic 07; AR-502, AR-506 pithic 07-09; AR-507 hic 10-12',
               'CA-515':'CA-527 hic 09', 'CA-516':'CA-528 pithic 10,11,12', 'CA-530':'CA-615 hic 15,16',
               'CA-601':'CA-610 hic 07-10', 'CA-611':'CA-605 hic 07-13',
               'CT-505':'CT-504, CT-507 hic 07-09; CT-500, CT-509, CT-510 hic 07-10; CT-501 hic 07-13; CT-512 hic 07-14; CT-502 hic 07-15',
               'CT-503':'CT-506, CT-508 hic 07-14',
               'FL-503':'FL-516 hic 08-14', 'IN-502':'IN-500 hic 07-16', 'KS-507':'KS-500 hic 07', 'LA-509':'LA-504 hic 07-16',
               'MA-516':'MA-512 hic 07-13; MA-513 hic 07-14; MA-518 hic 07-16',
               'MA-511':'MS-520 hic 07-14', 'ME-500':'ME-501 hic 07-11; ME-502 07-16', 'MI-500':'MI-521, MI-524 hic 07; MI-522 hic 07-08',
               'MN-503':'MN-507, MN-512 hic 07; MN-510 hic 07-10', 'MO-604':'KS-501 hic 07-15', 'MO-606':'MO-601 hic 07',
               'NC-503':'NC-508 hic 07-08', 'NE-500':'NE-503, NE-504, NE-505, NE-506 hic 07-10', 
               'NJ-503':'NJ-505, NJ-520 hic 07-13; NJ-518 hic 07-14', 'NJ-516':'NJ-519 hic 07-10',
               'NY-505':'NY-502 hic 07-15; NY-509 hic 09-14', 'NY-511':'NY-515 hic 07', 'NY-508':'NY-524 hic 07-12; NY-517 hic 07-14',
               'NY-518':'NY-521 hic 07', 'NY-603':'NY-605 07-11', 'OR-505':'OR-504 hic 07-10', 'PA-509':'PA-507 hic 07-14',
               'PA-601':'PA-602 hic 07-14', 'SC-503':'SC-504 hic 07-09', 
               'TX-607':'TX-613 hic 07-09; TX-705 hic 07-10; TX-610, TX-702 hic 07-11; TX-501, TX-504 hic 07-12; TX-703 hic 07-14',
               'VA-521':'VA-509, VA-510, VA-517 hic 07-12', 'VA-501':'VA-512, VA-519 hic 07-10', 'VA-513':'VA-518 hic 07-12',
               'WA-502':'WA-506 hic 07', 'IL-511':'IL-505 hic 07-10',
               'GA-GR1':'grouping of GA-500 all years; GA-502, GA-508 since 13',
               'MA-GR1':'grouping of MA-501 07-11; MA-504, MA-507 all years',
               'MA-GR2':'grouping of MA-514 07-09; MA-516, MA-517 all years'
              }

In [148]:
pitHicAllCocClean.reset_index(inplace=True)
pitHicAllCocClean['reflectsMerger'] = pitHicAllCocClean['cocNum'].apply(lambda x: mergerNotes[x] if x in mergerNotes else np.nan)
pitHicAllCocClean.set_index('cocNum', inplace=True)

pitHicAllCocCleanGroups.reset_index(inplace=True)
pitHicAllCocCleanGroups['reflectsMerger'] = pitHicAllCocCleanGroups['cocNum'].apply(lambda x: mergerNotes[x] if x in mergerNotes else np.nan)
pitHicAllCocCleanGroups.set_index('cocNum', inplace=True)

*Check results*

In [149]:
pitHicAllCocClean.loc['AR-503','reflectsMerger'].values[0]

'AR-509, AR-510 pithic 07; AR-502, AR-506 pithic 07-09; AR-507 hic 10-12'

In [150]:
pitHicAllCocCleanGroups.loc['MA-GR2','reflectsMerger'].values[0]

'grouping of MA-514 07-09; MA-516, MA-517 all years'

## Add column noting caution for comparison
*If more than 20 percent increase or decrease in CoC population as a result of the geography change, exclude*

In [151]:
compareOnlyUntil = {'AR-503':2013, 'AR-508':2014, 'AR-512':2010, 'CA-515':2009, 'CA-516':2015, 
                    'CA-523':2015, 'CA-527':2015, 'CA-529':2015, 'CA-615':2015, 'GA-500':2013,
                    'GA-502':2013, 'GA-506':2013, 'IL-506':2013, 'IL-512':2013, 'LA-509':2015,
                    'MA-504':2012, 'MA-507':2012, 'MA-517':2009, 'MA-518':2009, 'NY-501':2011,
                    'NY-505':2009, 'NY-511':2013, 'NY-518':2012, 'NY-520':2012, 'NY-522':2008,
                    'PA-512':2011, 'TX-503':2008
                   }

In [152]:
#Make temporary values being combination of coc number and year
pitHicAllCocClean.reset_index(inplace=True)
pitHicAllCocClean['comparable'] = pitHicAllCocClean['year'].map(str) + pitHicAllCocClean['cocNum']

pitHicAllCocCleanGroups.reset_index(inplace=True)
pitHicAllCocCleanGroups['comparable'] = pitHicAllCocCleanGroups['year'].map(str) + pitHicAllCocCleanGroups['cocNum']

pitHicAllCocClean.head(3)

,cocNum,st,cocName,year,totalH,shelH,unshelH,totalIndiv,shelIndiv,unshelIndiv,...,ophBedsDedVet,esBedsDedYouth,thBedsDedYouth,shBedsDedYouth,rrhBedsDedYouth,pshBedsDedYouth,ophBedsDedYouth,pshBedsDedCh,reflectsMerger,comparable
0,AK-500,AK,Anchorage CoC,2007,974.0,842.0,132.0,696.0,589.0,107.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,121.0,NaN,2007AK-500
1,AK-500,AK,Anchorage CoC,2008,1023.0,921.0,102.0,695.0,596.0,99.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,121.0,NaN,2008AK-500
2,AK-500,AK,Anchorage CoC,2009,1267.0,1110.0,157.0,821.0,689.0,132.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,27.0,NaN,2009AK-500

In [153]:
#define function that checks for coc number in dictionary, compares year to year in dictionary
def checkIfCompareCaution(x):
    coc = str(x[4:])
    year = int(x[:4])
    if coc in compareOnlyUntil:
        if compareOnlyUntil[coc] > year:
            return False
        else:
            return True
    else:
        return True

In [154]:
#apply the function
pitHicAllCocClean['comparable'] = pitHicAllCocClean['comparable'].map(lambda x: checkIfCompareCaution(x))
pitHicAllCocClean['cocComparableTo'] = pitHicAllCocClean['cocNum'].apply(lambda x: compareOnlyUntil[x] if x in compareOnlyUntil else np.nan)
pitHicAllCocClean.set_index('cocNum', inplace=True)

pitHicAllCocCleanGroups['comparable'] = pitHicAllCocCleanGroups['comparable'].map(lambda x: checkIfCompareCaution(x))
pitHicAllCocCleanGroups['cocComparableTo'] = pitHicAllCocCleanGroups['cocNum'].apply(lambda x: compareOnlyUntil[x] if x in compareOnlyUntil else np.nan)
pitHicAllCocCleanGroups.set_index('cocNum', inplace=True)

In [155]:
#check results for cocNum and year which should not be compared to later years
pitHicAllCocClean[pitHicAllCocClean['comparable']==False]

,st,cocName,year,totalH,shelH,unshelH,totalIndiv,shelIndiv,unshelIndiv,totalInFam,...,esBedsDedYouth,thBedsDedYouth,shBedsDedYouth,rrhBedsDedYouth,pshBedsDedYouth,ophBedsDedYouth,pshBedsDedCh,reflectsMerger,comparable,cocComparableTo
cocNum,,,,,,,,,,,,,,,,,,,,,
AR-503,AR,Arkansas Balance of State CoC,2007,510.0,196.0,314.0,380.0,134.0,246.0,130.0,...,NaN,NaN,NaN,NaN,NaN,NaN,3.0,"AR-509, AR-510 pithic 07; AR-502, AR-506 pithi...",False,2013.0
AR-503,AR,Arkansas Balance of State CoC,2008,184.0,77.0,107.0,108.0,37.0,71.0,76.0,...,NaN,NaN,NaN,NaN,NaN,NaN,113.0,"AR-509, AR-510 pithic 07; AR-502, AR-506 pithi...",False,2013.0
AR-503,AR,Arkansas Balance of State CoC,2009,186.0,56.0,130.0,138.0,48.0,90.0,48.0,...,NaN,NaN,NaN,NaN,NaN,NaN,113.0,"AR-509, AR-510 pithic 07; AR-502, AR-506 pithi...",False,2013.0
AR-503,AR,Arkansas Balance of State CoC,2010,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,7.0,"AR-509, AR-510 pithic 07; AR-502, AR-506 pithi...",False,2013.0
AR-503,AR,Arkansas Balance of State CoC,2011,943.0,605.0,338.0,754.0,499.0,255.0,189.0,...,NaN,NaN,NaN,NaN,NaN,NaN,7.0,"AR-509, AR-510 pithic 07; AR-502, AR-506 pithi...",False,2013.0
AR-503,AR,Arkansas Balance of State CoC,2012,1873.0,545.0,1328.0,1754.0,447.0,1307.0,119.0,...,NaN,NaN,NaN,NaN,NaN,NaN,7.0,"AR-509, AR-510 pithic 07; AR-502, AR-506 pithi...",False,2013.0
AR-508,AR,Old Fort Homeless Coalition,2007,194.0,147.0,47.0,157.0,111.0,46.0,37.0,...,NaN,NaN,NaN,NaN,NaN,NaN,4.0,NaN,False,2014.0
CA-515,CA,"Roseville/Rocklin/Placer, Nevada Counties CoC",2007,587.0,450.0,137.0,368.0,244.0,124.0,219.0,...,NaN,NaN,NaN,NaN,NaN,NaN,12.0,CA-527 hic 09,False,2009.0
CA-515,CA,"Roseville/Rocklin/Placer, Nevada Counties CoC",2008,587.0,450.0,137.0,368.0,244.0,124.0,219.0,...,NaN,NaN,NaN,NaN,NaN,NaN,5.0,CA-527 hic 09,False,2009.0
CA-516,CA,"Redding/Shasta, Siskiyou, Lassen, Plumas, Del ...",2007,296.0,250.0,46.0,147.0,121.0,26.0,149.0,...,NaN,NaN,NaN,NaN,NaN,NaN,28.0,"CA-528 pithic 10,11,12",False,2015.0
CA-516,CA,"Redding/Shasta, Siskiyou, Lassen, Plumas, Del ...",2008,263.0,201.0,62.0,186.0,131.0,55.0,77.0,...,NaN,NaN,NaN,NaN,NaN,NaN,17.0,"CA-528 pithic 10,11,12",False,2015.0
CA-516,CA,"Redding/Shasta, Siskiyou, Lassen, Plumas, Del ...",2009,340.0,194.0,146.0,205.0,90.0,115.0,135.0,...,NaN,NaN,NaN,NaN,NaN,NaN,25.0,"CA-528 pithic 10,11,12",False,2015.0
CA-516,CA,"Redding/Shasta, Siskiyou, Lassen, Plumas, Del ...",2010,354.0,233.0,121.0,247.0,156.0,91.0,107.0,...,NaN,NaN,NaN,NaN,NaN,NaN,34.0,"CA-528 pithic 10,11,12",False,2015.0
CA-516,CA,"Redding/Shasta, Siskiyou, Lassen, Plumas, Del ...",2011,975.0,383.0,592.0,719.0,266.0,453.0,256.0,...,NaN,NaN,NaN,NaN,NaN,NaN,44.0,"CA-528 pithic 10,11,12",False,2015.0
CA-516,CA,"Redding/Shasta, Siskiyou, Lassen, Plumas, Del ...",2012,961.0,358.0,603.0,689.0,232.0,457.0,272.0,...,NaN,NaN,NaN,NaN,NaN,NaN,34.0,"CA-528 pithic 10,11,12",False,2015.0
CA-516,CA,"Redding/Shasta, Siskiyou, Lassen, Plumas, Del ...",2013,851.0,504.0,347.0,631.0,361.0,270.0,220.0,...,NaN,NaN,NaN,NaN,NaN,NaN,34.0,"CA-528 pithic 10,11,12",False,2015.0
CA-516,CA,"Redding/Shasta, Siskiyou, Lassen, Plumas, Del ...",2014,630.0,548.0,82.0,461.0,384.0,77.0,169.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"CA-528 pithic 10,11,12",False,2015.0
CA-523,CA,"Colusa, Glenn, Trinity Counties CoC",2007,155.0,54.0,101.0,61.0,18.0,43.0,94.0,...,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,False,2015.0
CA-523,CA,"Colusa, Glenn, Trinity Counties CoC",2008,193.0,0.0,193.0,131.0,0.0,131.0,62.0,...,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,False,2015.0
CA-523,CA,"Colusa, Glenn, Trinity Counties CoC",2009,197.0,74.0,123.0,145.0,37.0,108.0,52.0,...,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,False,2015.0
CA-523,CA,"Colusa, Glenn, Trinity Counties CoC",2010,197.0,74.0,123.0,145.0,37.0,108.0,52.0,...,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,False,2015.0
CA-523,CA,"Colusa, Glenn, Trinity Counties CoC",2011,322.0,183.0,139.0,200.0,93.0,107.0,122.0,...,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,False,2015.0
CA-523,CA,"Colusa, Glenn, Trinity Counties CoC",2012,303.0,164.0,139.0,185.0,78.0,107.0,118.0,...,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,False,2015.0
CA-523,CA,"Colusa, Glenn, Trinity Counties CoC",2013,696.0,272.0,424.0,487.0,151.0,336.0,209.0,...,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,False,2015.0
CA-523,CA,"Colusa, Glenn, Trinity Counties CoC",2014,567.0,143.0,424.0,410.0,74.0,336.0,157.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,2015.0
GA-500,GA,Atlanta Continuum of Care,2007,6840.0,4725.0,2115.0,5622.0,3551.0,2071.0,1218.0,...,NaN,NaN,NaN,NaN,NaN,NaN,66.0,NaN,False,2013.0
GA-500,GA,Atlanta Continuum of Care,2008,6840.0,4725.0,2115.0,5622.0,3551.0,2071.0,1218.0,...,NaN,NaN,NaN,NaN,NaN,NaN,237.0,NaN,False,2013.0
GA-500,GA,Atlanta Continuum of Care,2009,7019.0,4855.0,2164.0,5781.0,3713.0,2068.0,1238.0,...,NaN,NaN,NaN,NaN,NaN,NaN,370.0,NaN,False,2013.0
GA-500,GA,Atlanta Continuum of Care,2010,7019.0,4855.0,2164.0,5781.0,3713.0,2068.0,1238.0,...,NaN,NaN,NaN,NaN,NaN,NaN,267.0,NaN,False,2013.0
GA-500,GA,Atlanta Continuum of Care,2011,6805.0,4427.0,2378.0,5732.0,3396.0,2336.0,1073.0,...,NaN,NaN,NaN,NaN,NaN,NaN,2209.0,NaN,False,2013.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
MA-504,MA,Springfield CoC,2011,1025.0,1020.0,5.0,291.0,286.0,5.0,734.0,...,NaN,NaN,NaN,NaN,NaN,NaN,208.0,NaN,False,2012.0
MA-507,MA,Pittsfield/Berkshire County CoC,2007,374.0,315.0,59.0,206.0,174.0,32.0,168.0,...,NaN,NaN,NaN,NaN,NaN,NaN,42.0,NaN,False,2012.0
MA-507,MA,Pittsfield/Berkshire County CoC,2008,237.0,210.0,27.0,181.0,159.0,22.0,56.0,...,NaN,NaN,NaN,NaN,NaN,NaN,41.0,NaN,False,2012.0
MA-507,MA,Pittsfield/Berkshire County CoC,2009,286.0,191.0,95.0,204.0,162.0,42.0,82.0,...,NaN,NaN,NaN,NaN,NaN,NaN,44.0,NaN,False,2012.0
MA-507,MA,Pittsfield/Berkshire County CoC,2010,280.0,193.0,87.0,164.0,142.0,22.0,116.0,...,NaN,NaN,NaN,NaN,NaN,NaN,29.0,NaN,False,2012.0
MA-507,MA,Pittsfield/Berkshire County CoC,2011,192.0,170.0,22.0,151.0,131.0,20.0,41.0,...,NaN,NaN,NaN,NaN,NaN,NaN,39.0,NaN,False,2012.0
MA-517,MA,Somerville CoC,2007,211.0,196.0,15.0,137.0,122.0,15.0,74.0,...,NaN,NaN,NaN,NaN,NaN,NaN,31.0,NaN,False,2009.0
MA-517,MA,Somerville CoC,2008,179.0,177.0,2.0,107.0,105.0,2.0,72.0,...,NaN,NaN,NaN,NaN,NaN,NaN,31.0,NaN,False,2009.0
NY-501,NY,"Elmira/Steuben, Allegany, Livingston, Chemung,...",2007,175.0,174.0,1.0,139.0,138.0,1.0,36.0,...,NaN,NaN,NaN,NaN,NaN,NaN,19.0,NaN,False,2011.0
NY-501,NY,"Elmira/Steuben, Allegany, Livingston, Chemung,...",2008,177.0,176.0,1.0,151.0,150.0,1.0,26.0,...,NaN,NaN,NaN,NaN,NaN,NaN,25.0,NaN,False,2011.0
NY-501,NY,"Elmira/Steuben, Allegany, Livingston, Chemung,...",2009,184.0,178.0,6.0,145.0,142.0,3.0,39.0,...,NaN,NaN,NaN,NaN,NaN,NaN,25.0,NaN,False,2011.0
NY-501,NY,"Elmira/Steuben, Allegany, Livingston, Chemung,...",2010,256.0,245.0,11.0,202.0,195.0,7.0,54.0,...,NaN,NaN,NaN,NaN,NaN,NaN,25.0,NaN,False,2011.0
NY-505,NY,"Syracuse, Auburn/Onondaga, Oswego, Cayuga Coun...",2007,795.0,762.0,33.0,634.0,617.0,17.0,161.0,...,NaN,NaN,NaN,NaN,NaN,NaN,242.0,NY-502 hic 07-15; NY-509 hic 09-14,False,2009.0
NY-505,NY,"Syracuse, Auburn/Onondaga, Oswego, Cayuga Coun...",2008,731.0,708.0,23.0,600.0,583.0,17.0,131.0,...,NaN,NaN,NaN,NaN,NaN,NaN,123.0,NY-502 hic 07-15; NY-509 hic 09-14,False,2009.0
NY-511,NY,"Binghamton, Union/Broome, Otsego, Chenango, De...",2007,243.0,203.0,40.0,212.0,177.0,35.0,31.0,...,NaN,NaN,NaN,NaN,NaN,NaN,65.0,NY-515 hic 07,False,2013.0
NY-511,NY,"Binghamton, Union/Broome, Otsego, Chenango, De...",2009,213.0,202.0,11.0,195.0,184.0,11.0,18.0,...,NaN,NaN,NaN,NaN,NaN,NaN,62.0,NY-515 hic 07,False,2013.0
NY-511,NY,"Binghamton, Union/Broome, Otsego, Chenango, De...",2010,234.0,223.0,11.0,211.0,200.0,11.0,23.0,...,NaN,NaN,NaN,NaN,NaN,NaN,62.0,NY-515 hic 07,False,2013.0
NY-511,NY,"Binghamton, Union/Broome, Otsego, Chenango, De...",2011,218.0,207.0,11.0,208.0,197.0,11.0,10.0,...,NaN,NaN,NaN,NaN,NaN,NaN,60.0,NY-515 hic 07,False,2013.0
NY-511,NY,"Binghamton, Union/Broome, Otsego, Chenango, De...",2012,292.0,281.0,11.0,283.0,272.0,11.0,9.0,...,NaN,NaN,NaN,NaN,NaN,NaN,60.0,NY-515 hic 07,False,2013.0
NY-518,NY,"Utica/Rome/Oneida, Madison Counties CoC",2007,334.0,318.0,16.0,193.0,177.0,16.0,141.0,...,NaN,NaN,NaN,NaN,NaN,NaN,20.0,NY-521 hic 07,False,2012.0
NY-518,NY,"Utica/Rome/Oneida, Madison Counties CoC",2008,316.0,300.0,16.0,186.0,170.0,16.0,130.0,...,NaN,NaN,NaN,NaN,NaN,NaN,20.0,NY-521 hic 07,False,2012.0
NY-518,NY,"Utica/Rome/Oneida, Madison Counties CoC",2009,343.0,326.0,17.0,251.0,234.0,17.0,92.0,...,NaN,NaN,NaN,NaN,NaN,NaN,20.0,NY-521 hic 07,False,2012.0
NY-518,NY,"Utica/Rome/Oneida, Madison Counties CoC",2010,343.0,326.0,17.0,251.0,234.0,17.0,92.0,...,NaN,NaN,NaN,NaN,NaN,NaN,18.0,NY-521 hic 07,False,2012.0
NY-518,NY,"Utica/Rome/Oneida, Madison Counties CoC",2011,182.0,160.0,22.0,99.0,91.0,8.0,83.0,...,NaN,NaN,NaN,NaN,NaN,NaN,34.0,NY-521 hic 07,False,2012.0
NY-520,NY,Franklin County CoC,2007,28.0,27.0,1.0,20.0,19.0,1.0,8.0,...,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,False,2012.0
NY-520,NY,Franklin County CoC,2008,10.0,6.0,4.0,10.0,6.0,4.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,18.0,NaN,False,2012.0
NY-520,NY,Franklin County CoC,2009,14.0,5.0,9.0,8.0,5.0,3.0,6.0,...,NaN,NaN,NaN,NaN,NaN,NaN,18.0,NaN,False,2012.0
NY-520,NY,Franklin County CoC,2010,14.0,5.0,9.0,8.0,5.0,3.0,6.0,...,NaN,NaN,NaN,NaN,NaN,NaN,18.0,NaN,False,2012.0
NY-520,NY,Franklin County CoC,2011,22.0,3.0,19.0,12.0,3.0,9.0,10.0,...,NaN,NaN,NaN,NaN,NaN,NaN,18.0,NaN,False,2012.0
TX-503,TX,Austin/Travis County CoC,2007,5281.0,1395.0,3886.0,3116.0,773.0,2343.0,2165.0,...,NaN,NaN,NaN,NaN,NaN,NaN,35.0,NaN,False,2008.0

<div class="mark">MAKE SURE THE ANALYSIS SCRIPTS ARE REFERENCING THESE, NOT THE ORIGINALS
</div><i class="fa fa-lightbulb-o "></i>

## Write to Excel

writer = pd.ExcelWriter('output_files_paso2_clean/pitHicAllCocClean.xlsx')
pitHicAllCocClean.to_excel(writer,'pitHicAllCocClean')
writer.save()

writer = pd.ExcelWriter('output_files_paso2_clean/pitHicAllCocCleanGroups.xlsx')
pitHicAllCocCleanGroups.to_excel(writer,'pitHicAllCocCleanGroups')
writer.save()

# "Clean" STATE data (same as import -- not necessary)

***Despite the MO/KS mismatch with CoC data, the original state data will probably be used in most analyses for retroactive consistency***<br>
<span class="girk">**For corrected MO/KS state data, can aggreggate CoC file, but caution that # of veterans is unavailable early years.**</span>

writer = pd.ExcelWriter('output_files_paso2_clean/pitHicAllStClean.xlsx')
pitHicAllStClean.to_excel(writer,'pitHicAllStClean')
writer.save()